apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv
  namespace: sonarqube
spec:
  storageClassName: sonarqube-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/sonarqube-volume/sonarqube

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-postgresql-pv
  namespace: sonarqube
spec:
  storageClassName: sonarqube-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/sonarqube-volume/postgresql


