apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  finalizers:
  labels:
  managedFields:
  name: sonarqube
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sonarqube-pv
  volumeMode: Filesystem
  volumeName: sonarqube-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  phase: Bound
