apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: neuvector-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: neuvector-data
    namespace: neuvector
  hostPath:
    path: /data/neuvector-volume/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: neuvector-data
  volumeMode: Filesystem
