apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neuvector-data
  namespace: neuvector
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: neuvector-data
  storageClassName: neuvector-data
  resources:
    requests:
      storage: 1Gi
