#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  annotations:
#  managedFields:
#  name: neuvector-data
#  namespace: neuvector
#spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#  storageClassName: neuvector-data
#  volumeMode: Filesystem
#  volumeName: neuvector-data

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neuvector-data
  namespace: neuvector
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: neuvector-data
  storageClassName: neuvector-data
  resources:
    requests:
      storage: 1Gi
