apiVersion: v1
kind: Service
metadata:
  name: neuvector-service-rest
  namespace: default
spec:
  ports:
    - port: 10443
      name: controller
      protocol: TCP
  type: NodePort
  selector:
    app: neuvector-controller-pod
