apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-data
  namespace: harbor
spec:
  storageClassName: harbor-data
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/harbor-data/
